In [1]:
import pandas as pd

In [2]:
def clean_emp_id(df):
    df.loc[:, "emp_id"] = (
        df.emp_id.astype(str)
        .str.lower()
        .str.strip()
        .str.replace(r"\s+", "", regex=True)
    )
    return df


def read_tbl():
    dfa = pd.read_csv(
        "../../../download/data/Oregon/or-2023-original-employment.csv"
    )
    dfb = pd.read_csv(
        "../../../download/data/Oregon/or-2023-original-employees.csv"
    )

    dfb = dfb[["emp_id", "sex", "ethnic", "ethnic_description"]]

    dfa = dfa[["emp_id", "action_description"]]

    dfa = dfa.pipe(clean_emp_id)
    dfb = dfb.pipe(clean_emp_id)

    dfc = pd.read_csv("../../../download/data/Oregon/Oregon_index.csv")

    dfc = dfc.rename(columns={"person_nbr": "emp_id"})

    dfc = dfc.pipe(clean_emp_id)

    df = pd.merge(dfa, dfc, on="emp_id")
    df = pd.merge(dfb, df, on="emp_id")
    df = df.rename(
        columns={
            "action_description": "separation_reason",
            "emp_id": "person_nbr",
        }
    )

    df = df.drop(
        columns=["age", "type", "birth_year", "suffix", "middle_name", "ethnic"]
    )
    df = df.rename(
        columns={"middle_initial": "middle_name", "ethnic_description": "race"}
    )
    return df


df = read_tbl()

df

/var/folders/4r/jhc99db14v58mjmncgtry0kc0000gn/T/ipykernel_12087/3294210775.py:6: DtypeWarning: Columns (20,21,28,29,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dfa = pd.read_csv("../../../download/data/Oregon/or-2023-original-employment.csv")
/var/folders/4r/jhc99db14v58mjmncgtry0kc0000gn/T/ipykernel_12087/3294210775.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['56' '56' '56' ... '63312' '63313' '63314']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, "emp_id"] = df.emp_id.astype(str).str.lower().str.strip().str.replace(r"\s+", "", regex=True)
/var/folders/4r/jhc99db14v58mjmncgtry0kc0000gn/T/ipykernel_12087/3294210775.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['56' '141' '174' ... '63312' '63313' '63314']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, "emp_id"] = df.emp_id.astype(str).str.lower().str.strip().str.replace(r"\s+", "", regex=True)
/var/folders/4r/jhc99db14v58mjmncgtry0kc0000gn/T/ipykernel_12087/3294210775.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['57' '57' '142' ... '64534' '64535' '64536']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, "emp_id"] = df.emp_id.astype(str).str.lower().str.strip().str.replace(r"\s+", "", regex=True)

,person_nbr,sex,race,separation_reason,full_name,last_name,first_name,middle_name,agency_name,rank,start_date,end_date
0,3086,M,WHITE,HIRED,DOUGLAS C RATHBUN,RATHBUN,DOUGLAS,C,COOS COUNTY SHERIFF'S OFFICE,DEPUTY SHERIFF,1972-10-01,1973-05-01
1,3086,M,WHITE,HIRED,DOUGLAS C RATHBUN,RATHBUN,DOUGLAS,C,GASTON POLICE DEPARTMENT,CHIEF,1967-05-15,1968-08-15
2,3086,M,WHITE,HIRED,DOUGLAS C RATHBUN,RATHBUN,DOUGLAS,C,HEPPNER POLICE DEPARTMENT,POLICE OFFICER,1975-02-19,1977-09-21
3,3086,M,WHITE,HIRED,DOUGLAS C RATHBUN,RATHBUN,DOUGLAS,C,HEPPNER POLICE DEPARTMENT,CHIEF,1984-01-01,2001-06-30
4,3086,M,WHITE,HIRED,DOUGLAS C RATHBUN,RATHBUN,DOUGLAS,C,POWERS POLICE DEPARTMENT,CHIEF,1968-08-20,1974-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...
64173,63311,M,NaN,HIRED,ALEJANDRO CASTANEDA,CASTANEDA,ALEJANDRO,NaN,WASHINGTON COUNTY SHERIFF'S OFFICE,DEPUTY SHERIFF,2021-07-05,NaN
64174,63313,F,NaN,HIRED,JOHN F GERDES,GERDES,JOHN,F,KLAMATH COUNTY SHERIFF'S OFFICE,DEPUTY SHERIFF,2021-07-19,NaN
64175,63314,F,NaN,HIRED,RUBY M ESTRADA-SANCHEZ,ESTRADA-SANCHEZ,RUBY,M,BEAVERTON POLICE DEPARTMENT,RESERVE OFFICER,2021-07-14,NaN
64176,63314,F,NaN,HIRED,RUBY M ESTRADA-SANCHEZ,ESTRADA-SANCHEZ,RUBY,M,BEAVERTON POLICE DEPARTMENT,CORRECTIONS OFFICER,2021-11-03,NaN
64177,63314,F,NaN,HIRED,RUBY M ESTRADA-SANCHEZ,ESTRADA-SANCHEZ,RUBY,M,BEAVERTON POLICE DEPARTMENT,POLICE OFFICER,2022-08-01,NaN

In [3]:
df.to_csv("../data/output/oregon_index.csv", index=False)