In [1]:
import pandas as pd

In [2]:
def read_tbl():
    df = pd.read_csv("../data/output/georgia_index.csv")

    df = df.rename(columns={"agcy_name": "agency_name"})
    return df


df = read_tbl()

df


# with gzip.open("../data/output/georgia-processed.csv.gz", 'wt') as f:
#     df.to_csv(f, index=False)

,person_nbr,full_name,employment_status,start_date,end_date,first_name,middle_name,last_name,suffix,rank,birth_year,agency_name
0,O246465,AAMIR WISHAH,ACTIVELY EMPLOYED IN LAW ENFORCEMENT,2020-06-01,0000-00-00,AAMIR,NaN,WISHAH,NaN,COMMUNICATIONS OFFICER,1996,ELBERT COUNTY 911
1,O095227,AANERUD H DAMON,VOLUNTARY RESIGNATION,1999-04-19,2000-10-07,AANERUD,H,DAMON,NaN,JAILOR,1972,CHATHAM COUNTY SHERIFFS OFFICE
2,O095227,AANERUD H DAMON,VOLUNTARY RESIGNATION,2000-10-09,2001-03-30,AANERUD,H,DAMON,NaN,PEACE OFFICER,1972,SAVANNAH POLICE DEPARTMENT
3,O095227,AANERUD H DAMON,RANK CHANGE - PROMOTION,2001-03-10,2009-09-27,AANERUD,H,DAMON,NaN,CORPORAL,1972,POOLER POLICE DEPARTMENT
4,O095227,AANERUD H DAMON,ACTIVELY EMPLOYED IN LAW ENFORCEMENT,2009-09-28,0000-00-00,AANERUD,H,DAMON,NaN,SERGEANT,1972,POOLER POLICE DEPARTMENT
...,...,...,...,...,...,...,...,...,...,...,...,...
134658,O136250,ZYDONYK L ASHBY,RANK CHANGE - PROMOTION,2020-01-20,2021-01-01,ZYDONYK,L,ASHBY,NaN,CAPTAIN,1985,NEWINGTON POLICE DEPARTMENT
134659,O136250,ZYDONYK L ASHBY,ACTIVELY EMPLOYED IN LAW ENFORCEMENT,2021-01-01,0000-00-00,ZYDONYK,L,ASHBY,NaN,CHIEF,1985,NEWINGTON POLICE DEPARTMENT
134660,O110791,ZYGAJ M STEPHEN,RANK CHANGE - PROMOTION,2001-12-18,2020-01-08,ZYGAJ,M,STEPHEN,NaN,PEACE OFFICER,1962,ATLANTA POLICE DEPARTMENT
134661,O110791,ZYGAJ M STEPHEN,RANK CHANGE - PROMOTION,2020-01-09,2022-04-13,ZYGAJ,M,STEPHEN,NaN,CAPTAIN,1962,ATLANTA POLICE DEPARTMENT
134662,O110791,ZYGAJ M STEPHEN,ACTIVELY EMPLOYED IN LAW ENFORCEMENT,2022-04-14,0000-00-00,ZYGAJ,M,STEPHEN,NaN,MAJOR,1962,ATLANTA POLICE DEPARTMENT

In [3]:
df.to_csv("../../../../download/data/georgia/georgia_index.csv", index=False)