In [13]:
import pandas as pd

In [14]:
def read_tbl():
    df = pd.read_csv("../../../download/data/California/California_index.csv")

    df = df.rename(columns={"agcy_name": "agency_name"})

    return df 

df = read_tbl()

df

/var/folders/4r/jhc99db14v58mjmncgtry0kc0000gn/T/ipykernel_9527/870184166.py:2: DtypeWarning: Columns (0,4,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../../download/data/California/California_index.csv")

,person_nbr,full_name,last_name,first_name,middle_name,middle_initial,suffix,agency_name,type,rank,start_date,end_date
0,B00-P18,PATRICK E RICHARDSON,RICHARDSON,PATRICK,E,E,NaN,GLENDALE PD,POLICE,PO,1979-07-03,1982-06-11
1,B00-P18,PATRICK E RICHARDSON,RICHARDSON,PATRICK,E,E,NaN,BEVERLY HILLS PD,POLICE,PO,1982-06-14,1982-09-24
2,B00-P18,PATRICK E RICHARDSON,RICHARDSON,PATRICK,E,E,NaN,GLENDALE PD,POLICE,PO,1982-09-26,2007-07-12
3,B22-C55,DANIEL WILLIARD HARVEY,HARVEY,DANIEL,WILLIARD,W,NaN,SEASIDE PD,POLICE,SGT,1965-05-01,1991-09-30
4,A68-P63,ROBERT DON PRICE,PRICE,ROBERT,DON,D,NaN,LOS ANGELES PD,POLICE,PO,1993-01-22,2014-08-10
...,...,...,...,...,...,...,...,...,...,...,...,...
584873,293927,LUCIO HERRERA ORTEGA,HERRERA ORTEGA,LUCIO,NaN,NaN,NaN,934: HIGH DESERT STATE PRISON,CORRECTIONS,662: CORRECTIONAL OFFICER,2019-04-01,NaN
584874,293928,JOSE F DIAZ PENALOZA,DIAZ PENALOZA,JOSE,NaN,F,NaN,048: RA MCGEE CORR TRAIN CNTR -AKA- RICHARD A ...,CORRECTIONS,662: CORRECTIONAL OFFICER,2023-03-20,NaN
584875,293928,JOSE F DIAZ PENALOZA,DIAZ PENALOZA,JOSE,NaN,F,NaN,095: SAN QUENTIN STATE PRISON,CORRECTIONS,662: CORRECTIONAL OFFICER,2023-06-19,NaN
584876,293929,CRISTIAN G GAMBOA,GAMBOA,CRISTIAN,NaN,G,NaN,048: RA MCGEE CORR TRAIN CNTR -AKA- RICHARD A ...,CORRECTIONS,662: CORRECTIONAL OFFICER,2019-10-15,NaN
584877,293929,CRISTIAN G GAMBOA,GAMBOA,CRISTIAN,NaN,G,NaN,674: CA. STATE PRISON - SOLANO,CORRECTIONS,662: CORRECTIONAL OFFICER,2020-01-27,NaN

In [15]:
df.to_csv("../data/output/california_index.csv", index=False)

In [16]:
df.isna().sum()

person_nbr             0
full_name              0
last_name             30
first_name          2187
middle_name       228625
middle_initial    117716
suffix            565296
agency_name            0
type                   0
rank                   8
start_date            86
end_date          191318
dtype: int64