In [25]:
# person_nbr
# full_name
# last_name
# first_name
# middle_name
# middle_initial
# suffix
# birth_year
# dob
# age
# agcy_name
# type
# rank
# start_date
# end_date


## read me

# 1. Drop rows where both start_date and end_date are empty strings

# 2. keep rows where start date is an empty string because end date might be present, incidating that the officer once worked at that given agency

# 3. drop asterisks from uid

# 4. (.+)fire(.+)

In [26]:
import pandas as pd

In [27]:
# def read_csv():
#     df_header = pd.read_csv("../../../data/TN/23-6-1/tn_ad-hoc-export-2023-filtered-20231220144255.csv", nrows=0)
#     first_100_columns = df_header.columns[:127]
#     df = pd.read_excel("../../../data/TN/23-6-1/tn_ad-hoc-export-2023-filtered-20231220144255.xlsx", usecols=first_100_columns)
#     df = df[~((df["Person PSID"].fillna("") == ""))]
#     return df

# df = read_csv()

# original_columns = df.columns

# original_columns

# # Define the new column names
# new_columns = [
#     'Person PSID', 'Person First Name', 'Person Middle Name', 'Person Last Name', 'Person Suffix', 'Person Gender',
#     'Employment Start Date_0', 'Employment End Date_0', 'Employment Appointment Type_0', 'Employment Employment Type_0',
#     'Employment Title/Rank (Current)_0', 'Employment Status_0', 'Employment Change Reason_0', 'Employment Change Comment_0',
#     'Is Primary Employment_0', 'Employing Organization Name_0', 'Employing Organization ID_0',
#     'Employment Start Date_1', 'Employment End Date_1', 'Employment Appointment Type_1', 'Employment Employment Type_1',
#     'Employment Title/Rank (Current)_1', 'Employment Status_1', 'Employment Change Reason_1', 'Employment Change Comment_1',
#     'Is Primary Employment_1', 'Employing Organization Name_1', 'Employing Organization ID_1',
#     'Employment Start Date_2', 'Employment End Date_2', 'Employment Appointment Type_2', 'Employment Employment Type_2',
#     'Employment Title/Rank (Current)_2', 'Employment Status_2', 'Employment Change Reason_2', 'Employment Change Comment_2',
#     'Is Primary Employment_2', 'Employing Organization Name_2', 'Employing Organization ID_2',
#     'Employment Start Date_3', 'Employment End Date_3', 'Employment Appointment Type_3', 'Employment Employment Type_3',
#     'Employment Title/Rank (Current)_3', 'Employment Status_3', 'Employment Change Reason_3', 'Employment Change Comment_3',
#     'Is Primary Employment_3', 'Employing Organization Name_3', 'Employing Organization ID_3',
#     'Employment Start Date_4', 'Employment End Date_4', 'Employment Appointment Type_4', 'Employment Employment Type_4',
#     'Employment Title/Rank (Current)_4', 'Employment Status_4', 'Employment Change Reason_4', 'Employment Change Comment_4',
#     'Is Primary Employment_4', 'Employing Organization Name_4', 'Employing Organization ID_4',
#     'Employment Start Date_5', 'Employment End Date_5', 'Employment Appointment Type_5', 'Employment Employment Type_5',
#     'Employment Title/Rank (Current)_5', 'Employment Status_5', 'Employment Change Reason_5', 'Employment Change Comment_5',
#     'Is Primary Employment_5', 'Employing Organization Name_5', 'Employing Organization ID_5',
#     'Employment Start Date_6', 'Employment End Date_6', 'Employment Appointment Type_6', 'Employment Employment Type_6',
#     'Employment Title/Rank (Current)_6', 'Employment Status_6', 'Employment Change Reason_6', 'Employment Change Comment_6',
#     'Is Primary Employment_6', 'Employing Organization Name_6', 'Employing Organization ID_6',
#     'Employment Start Date_7', 'Employment End Date_7', 'Employment Appointment Type_7', 'Employment Employment Type_7',
#     'Employment Title/Rank (Current)_7', 'Employment Status_7', 'Employment Change Reason_7', 'Employment Change Comment_7',
#     'Is Primary Employment_7', 'Employing Organization Name_7', 'Employing Organization ID_7',
#     'Employment Start Date_8', 'Employment End Date_8', 'Employment Appointment Type_8', 'Employment Employment Type_8', 'Employment Title/Rank (Current)_8', 'Employment Status_8', 'Employment Change Reason_8', 'Employment Change Comment_8', 'Is Primary Employment_8', 'Employing Organization Name_8', 'Employing Organization ID_8',
#     'Employment Start Date_9', 'Employment End Date_9', 'Employment Appointment Type_9', 'Employment Employment Type_9', 'Employment Title/Rank (Current)_9', 'Employment Status_9', 'Employment Change Reason_9', 'Employment Change Comment_9', 'Is Primary Employment_9', 'Employing Organization Name_9', 'Employing Organization ID_9',
#     'Employment Start Date_10', 'Employment End Date_10', 'Employment Appointment Type_10', 'Employment Employment Type_10', 'Employment Title/Rank (Current)_10', 'Employment Status_10', 'Employment Change Reason_10', 'Employment Change Comment_10', 'Is Primary Employment_10', 'Employing Organization Name_10', 'Employing Organization ID_10',
# ]

# df = df.rename(columns=dict(zip(original_columns, new_columns)))

In [28]:
# colz = df.columns.to_list()

# colz

In [29]:
# Get the identifying columns
# id_cols = ['Person PSID', 'Person First Name', 'Person Middle Name', 'Person Last Name', 'Person Suffix', 'Person Gender']

# split_rows = []

# for _, row in df.iterrows():
#     for i in range(11):
#         new_row = row[id_cols].tolist()
        
#         for col in df.columns:
#             if col.endswith(f'_{i}'):
#                 new_row.append(row[col])
        
#         split_rows.append(new_row)

# cols_0 = [col for col in df.columns if col.endswith('_0')]

# new_df = pd.DataFrame(split_rows, columns=id_cols + [col.rsplit('_', 1)[0] for col in cols_0])
new_df = pd.read_csv("for_cleaning.csv")

In [30]:
# drop rows missing start date

new_df

,Person PSID,Person First Name,Person Middle Name,Person Last Name,Person Suffix,Person Gender,Employment Start Date,Employment End Date,Employment Appointment Type,Employment Employment Type,Employment Title/Rank (Current),Employment Status,Employment Change Reason,Employment Change Comment,Is Primary Employment,Employing Organization Name,Employing Organization ID
0,***33814,Mark,J.,Binkley,NaN,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,***33814,Mark,J.,Binkley,NaN,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,***33814,Mark,J.,Binkley,NaN,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,***33814,Mark,J.,Binkley,NaN,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,***33814,Mark,J.,Binkley,NaN,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1258362,9999,Jennifer,NaN,Pack,NaN,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1258363,9999,Jennifer,NaN,Pack,NaN,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1258364,9999,Jennifer,NaN,Pack,NaN,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1258365,9999,Jennifer,NaN,Pack,NaN,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1258366,9999,Jennifer,NaN,Pack,NaN,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
newest_df = new_df.rename(columns={"Person PSID": "person_nbr", 
                                "Person First Name": "first_name", 
                                "Person Middle Name": "middle_name", 
                                "Person Last Name": "last_name", 
                                "Employing Organization Name": "agcy_name", 
                                "Employment Change Reason": "type", 
                                "Employment Title/Rank (Current)": "rank", 
                                "Employment Start Date": "start_date", 
                                "Employment End Date": "end_date"})


newest_df = newest_df[["person_nbr", "first_name", "middle_name", "last_name", "agcy_name", "type", "rank", "start_date", "end_date"]]

newest_df.loc[:, "full_name"] = (
    newest_df.first_name.astype(str).fillna("") + " " +
    newest_df.middle_name.astype(str).fillna("") + " " +
    newest_df.last_name.astype(str).fillna("")
).str.strip()

## remove nans in full_name

newest_df

,person_nbr,first_name,middle_name,last_name,agcy_name,type,rank,start_date,end_date,full_name
0,***33814,Mark,J.,Binkley,NaN,NaN,NaN,NaN,NaN,Mark J. Binkley
1,***33814,Mark,J.,Binkley,NaN,NaN,NaN,NaN,NaN,Mark J. Binkley
2,***33814,Mark,J.,Binkley,NaN,NaN,NaN,NaN,NaN,Mark J. Binkley
3,***33814,Mark,J.,Binkley,NaN,NaN,NaN,NaN,NaN,Mark J. Binkley
4,***33814,Mark,J.,Binkley,NaN,NaN,NaN,NaN,NaN,Mark J. Binkley
...,...,...,...,...,...,...,...,...,...,...
1258362,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,NaN,NaN,Jennifer nan Pack
1258363,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,NaN,NaN,Jennifer nan Pack
1258364,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,NaN,NaN,Jennifer nan Pack
1258365,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,NaN,NaN,Jennifer nan Pack
1258366,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,NaN,NaN,Jennifer nan Pack

In [32]:
# Convert start_date and end_date to datetime format, coercing invalid dates to NaT
newest_df['start_date'] = pd.to_datetime(newest_df['start_date'], errors='coerce')
newest_df['end_date'] = pd.to_datetime(newest_df['end_date'], errors='coerce')

# Extract only the date part
newest_df['start_date'] = newest_df['start_date'].dt.date
newest_df['end_date'] = newest_df['end_date'].dt.date

# Format the dates as 'YYYY-MM-DD', handling NaT values
newest_df['start_date'] = newest_df['start_date'].apply(lambda x: x.strftime('%Y-%m-%d') if not pd.isnull(x) else '')
newest_df['end_date'] = newest_df['end_date'].apply(lambda x: x.strftime('%Y-%m-%d') if not pd.isnull(x) else '')

newest_df

/var/folders/4r/jhc99db14v58mjmncgtry0kc0000gn/T/ipykernel_17410/2472124367.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  newest_df['start_date'] = pd.to_datetime(newest_df['start_date'], errors='coerce')

,person_nbr,first_name,middle_name,last_name,agcy_name,type,rank,start_date,end_date,full_name
0,***33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
1,***33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
2,***33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
3,***33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
4,***33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
...,...,...,...,...,...,...,...,...,...,...
1258362,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack
1258363,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack
1258364,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack
1258365,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack
1258366,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack

In [33]:
# Drop rows where both start_date and end_date are empty strings


### keep rows where start date is an empty string because end date might be present, incidating that the officer once worked at that given agency

## drop asterisks from uid
newest_df.loc[:, "person_nbr"] = newest_df.person_nbr.astype(str).str.replace(r"^\*\*", "", regex=True)


newest_df

,person_nbr,first_name,middle_name,last_name,agcy_name,type,rank,start_date,end_date,full_name
0,*33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
1,*33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
2,*33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
3,*33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
4,*33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
...,...,...,...,...,...,...,...,...,...,...
1258362,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack
1258363,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack
1258364,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack
1258365,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack
1258366,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack

In [34]:
newest_df.loc[:, "agcy_name"] = (newest_df.agcy_name
                                 .str.lower()
                                 .str.strip()
                                 .str.replace(r"^ (\w+)", r"\1", regex=True)
                                 .str.replace(r"(\w+) $", r"\1", regex=True)
                                 .str.replace(r"(.+)\btbd\b(.+)", "", regex=True)
                                 .str.replace(r"(.+)?fire(.+)?", "", regex=True)
                                 .str.replace(r"(.+) vfd-? ?(.+)?", "", regex=True)
                                 .str.replace(r"dept\.?", "department", regex=True)
                                 .str.replace(r"(\w+) \btn\b (\w+)", r"\1 tennessee \2", regex=True)
                                 .str.replace(r"comm\.? college", "community college", regex=True)
                                 .str.replace(r"^tn ", "tennesee ", regex=True)
                                 .str.replace(r" & ", " and ", regex=False)
                                 .str.replace(r"(.+)\bems\b(.+)", "" ,regex=True)
                                 .str.replace(r"(.+) ems$", "" ,regex=True)
                                 .str.replace(r" tn$", " tennesee", regex=True)
                                )

newest_df

,person_nbr,first_name,middle_name,last_name,agcy_name,type,rank,start_date,end_date,full_name
0,*33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
1,*33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
2,*33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
3,*33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
4,*33814,Mark,J.,Binkley,NaN,NaN,NaN,,,Mark J. Binkley
...,...,...,...,...,...,...,...,...,...,...
1258362,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack
1258363,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack
1258364,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack
1258365,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack
1258366,9999,Jennifer,NaN,Pack,NaN,NaN,NaN,,,Jennifer nan Pack

In [35]:
unique_agency_names = newest_df['agcy_name'].unique().tolist()

unique_agency_names

[nan,
 '',
 'kingsport police department',
 "benton county sheriff's office",
 "cocke county sheriff's office",
 "williamson county sheriff's office",
 'metro nashville police department',
 'spring hill police department',
 'memphis police department',
 "humphreys county sheriff's office",
 'dickson police department',
 'chattanooga police department',
 'smyrna police department',
 'murfreesboro police department',
 'clarksville police department',
 "hamilton county sheriff's office",
 'jackson police department',
 'new johnsonville police department',
 'manchester police department',
 "rutherford county sheriff's office",
 'tri-cities airport authority police department',
 'paris police department',
 "knox county sheriff's office",
 'u.t. knoxville police department',
 'vanderbilt university police department',
 'east tennessee state university department of public safety',
 "mcminn county sheriff's office",
 'law enforcement officers safety act',
 "jefferson county sheriff's office",
 'powells crossroads police department',
 "marion county sheriff's office",
 "sullivan county sheriff's office",
 "shelby county sheriff's office",
 'gallatin police department',
 'tennesee state parks',
 'austin peay state university police department',
 "macon county sheriff's office",
 'red boiling springs police department',
 "bradley county sheriff's office",
 'lakewood police department',
 'lavergne police department',
 'greenbrier police department',
 'signal mountain police department',
 "fayette county sheriff's office",
 'chattanooga state community college campus police department',
 'humboldt police department',
 'bolivar police department',
 'gatlinburg police department',
 'middle tennessee state university police department',
 "giles county sheriff's office",
 'tullahoma police department',
 'ducktown codes department',
 'south pittsburg police department',
 'livingston police department',
 'bartlett police department',
 "sumner county sheriff's office",
 'franklin police department',
 'tennesee highway patrol',
 'portland police department',
 'madisonville police department',
 "monroe county sheriff's office",
 'oak ridge police department',
 "sequatchie county sheriff's office",
 'dunlap police department',
 'cleveland police department',
 "hardeman county sheriff's office",
 "haywood county sheriff's office",
 'harriman police department',
 "white county sheriff's office",
 'jasper police department',
 "campbell county sheriff's office",
 'motlow state community college campus police department',
 'williamson county rescue squad',
 'alexandria police department',
 "dekalb county sheriff's office",
 'smithville police department',
 'johnson city police department',
 'columbia police department',
 'monterey police department',
 "putnam county sheriff's office",
 "overton county sheriff's office",
 'cookeville police department',
 "fentress county sheriff's office",
 "crockett county sheriff's office",
 "blount county sheriff's office",
 "hickman county sheriff's office",
 "carter county sheriff's office",
 'hamilton county parks and recreation',
 'collierville police department',
 'u.t. memphis police department',
 'bristol police department',
 'milan police department',
 'covington police department',
 'atoka police department',
 'brighton police department',
 "lauderdale county sheriff's office",
 "polk county sheriff's office",
 'tennessee law enforcement training academy',
 "mcnairy county sheriff's office",
 'bluff city police department',
 'elizabethton police department',
 "van buren county sheriff's office",
 'knoxville police department',
 "cheatham county sheriff's office",
 "cannon county sheriff's office",
 'millersville police department',
 "roane county sheriff's office",
 'kingston police department',
 'morristown police department',
 "grundy county sheriff's office",
 "greene county sheriff's office",
 "sevier county sheriff's office",
 "washington county sheriff's office",
 'brentwood police department',
 "maury county sheriff's office",
 'metro nashville codes 2nd ave',
 'greeneville police department',
 'south carthage police department',
 'athens police department',
 'east ridge police department',
 'union city police department',
 'mt. juliet police department',
 'lebanon police department',
 "warren county sheriff's office",
 'dover police department',
 "lawrence county sheriff's office",
 'huntingdon police department',
 "carroll county sheriff's office",
 "johnson county sheriff's office",
 'germantown police department',
 "perry county sheriff's office",
 'hollow rock police department',
 'ridgetop police department',
 "robertson county sheriff's office",
 'centerville police department',
 "coffee county sheriff's office",
 'arnold air force base police department',
 "anderson county sheriff's office",
 'tellico plains police department',
 'englewood police department',
 "hawkins county sheriff's office",
 'rogersville police department',
 'munford police department',
 "meigs county sheriff's office",
 'springfield police department',
 'nolensville police department',
 "smith county sheriff's office",
 'winchester police department',
 'decherd police department',
 'pleasant view police department',
 'u.t. chattanooga police department',
 'carthage police department',
 'university of memphis department of public safety',
 'fairview police department',
 'metro nashville airport department of public safety',
 'gordonsville police department',
 'nashville state community college police department',
 "montgomery county sheriff's office",
 "wilson county sheriff's office",
 "scott county sheriff's office",
 'alcoa police department',
 "union county sheriff's office",
 'greeneville county university ridge (sc)',
 'obion police department',
 "morgan county sheriff's office",
 'oneida police department',
 'tennesee department of revenue special investigations',
 'graysville police department',
 "franklin county sheriff's office",
 'maynardville police department',
 "pickett county sheriff's office",
 'monteagle police department',
 'southwest tennessee community college campus police department',
 'oliver springs police department',
 'tennesee highwary patrol training academy',
 'mckenzie police department',
 'dyersburg police department',
 'halls police department',
 'dandridge police department',
 'sevierville police department',
 'mcminnville police department',
 'spencer police department',
 'south fulton police department',
 'tennessee state university police department',
 'henning police department',
 'lawrenceburg police department',
 "dickson county sheriff's office",
 'grainger county rescue squad',
 "madison county sheriff's office",
 'lincoln memorial university campus police department',
 'rocky top police department',
 'lewisburg police department',
 "henry county sheriff's office",
 'shelbyville police department',
 'wilson county ema',
 "chester county sheriff's office",
 'erin police department',
 'etowah police department',
 'millington police department',
 'belle meade police department',
 'coopertown police department',
 'dyer police department',
 'red bank police department',
 'pikeville police department',
 'goodlettsville police department',
 'jefferson city police department',
 'caryville police department',
 'troy police department',
 'union county rescue squad',
 "gibson county sheriff's office",
 'trenton police department',
 "decatur county sheriff's office",
 "henderson county sheriff's office",
 'parsons police department',
 'scotts hill police department',
 'town of wartrace',
 'hamilton county building and zoning',
 'tazewell police department',
 "claiborne county sheriff's office",
 "grainger county sheriff's office",
 'city of franklin',
 'hendersonville police department',
 'hamilton county emergency services',
 'monroe county rescue squad',
 'chattanooga metropolitan airport police',
 'u.t. martin police department',
 'tennesee bureau of investigation',
 'rutledge police department',
 'bean station police department',
 "loudon county sheriff's office",
 'regional organized crime information center',
 'clinton police department',
 "lewis county sheriff's office",
 'jonesborough police department',
 'church hill police department',
 'mcewen police department',
 'maryville police department',
 'loudon police department',
 'pulaski police department',
 'chapel hill police department',
 'sparta police department',
 'clarksville building and codes department',
 'volunteer state community college campus police department',
 'tracy city police department',
 "lake county sheriff's office",
 'ripley police department',
 "bedford county sheriff's office",
 'brownsville police department',
 'tennesee tech university police department',
 'medina police department',
 'memphis/shelby airport authority police department',
 "unicoi county sheriff's office",
 "cumberland county sheriff's office",
 'pigeon forge police department',
 'metro nashville parks and recreation',
 'walters state community college campus police department',
 'dover public safety',
 'ethridge police department',
 'townsend police department',
 'oakland police department',
 'city of knoxville plans review and inspection',
 'cumberland gap police department',
 'new tazewell police department',
 'sharon police department',
 'somerville police department',
 'belmont university campus security',
 'berry hill police department',
 'spring city police department',
 'out of state agency',
 'watertown police department',
 'tennesee bureau of investigation/bomb and arson',
 'dayton police department',
 'gates police department',
 'algood police department',
 'bledsoe county correctional complex',
 'hohenwald police department',
 'lexington police department',
 'union pacific railroad police department',
 'eastman chemical company',
 'rockwood police department',
 'kenton police department',
 'bradford police department',
 'crossville police department',
 'blaine police department',
 "hamblen county sheriff's office",
 "rhea county sheriff's office",
 "wayne county sheriff's office",
 'vonore police department',
 "marshall county sheriff's office",
 "jackson county sheriff's office",
 'whitwell police department',
 'gruetli-laager police department',
 'nuclear fuel services',
 'cornersville police department',
 'elkton police department',
 'roane county office of emergency services',
 "hancock county sheriff's office",
 'lafollette police department',
 'gleason police department',
 'greenfield police department',
 'nolensville codes',
 'jacksboro police department',
 'cumberland city police department',
 "moore county sheriff's office",
 'tennesee sheriffs association',
 'tennesee meth task force',
 'ardmore police department',
 'metro knoxville airport public safety department',
 'csx railroad police department',
 'huntland police department',
 'fayetteville police department',
 'fairfield glade public safety',
 'bristol codes enforcement division (city of)',
 'baxter police department',
 'hartsville police department',
 'city of fayetteville',
 "obion county sheriff's office",
 'piperton police department',
 'decaturville (town/city of)',
 'savannah police department',
 'memphis and shelby county code enforcement',
 'city of harrogate',
 "trousdale county sheriff's office",
 'lenoir city police department',
 'sweetwater police department',
 'westmoreland police department',
 "hardin county sheriff's office",
 'carter county planning office',
 'mount pleasant police department',
 'martin police department',
 'henderson police department',
 'bruceton police department',
 'pellissippi state community college',
 'gallaway police department',
 'northeast state community college police department',
 "tipton county sheriff's office",
 'cowan police department',
 'sewanee university of the south campus police department',
 'lafayette police department',
 'goodlettsville codes department',
 "stewart county sheriff's office",
 'niota police department',
 'christian brothers university campus police department',
 'waynesboro police department',
 'cleveland state community college campus police department',
 'jellico life saving and rescue squad',
 'tdot-memphis',
 'selmer police department',
 'mason police department',
 'claxton community ves',
 'roane state community college police department',
 "lincoln county sheriff's office",
 'celina police department',
 "clay county sheriff's office",
 'tennesee emergency management agency',
 'soddy-daisy police department',
 'newport police department',
 "weakley county sheriff's office",
 'dresden police department',
 'calhoun police department',
 'copperhill police department',
 'erwin police department',
 '12th judicial district drug task force',
 'tdot-nashville',
 'tiptonville police department',
 'adamsville police department',
 'jellico police department',
 'white house police department',
 'collegedale police department',
 'petersburg police department',
 'palmer police department',
 "dyer county sheriff's office",
 'newbern police department',
 '24th judicial district drug task force',
 'loretto police department',
 'west tennessee violent crime and drug task force',
 'memphis housing authority',
 'metro-nashville/davidson co. codes administration',
 'benton police department',
 'dea',
 "houston county sheriff's office",
 'norris police department',
 'east tennessee state university',
 'town of unicoi police department',
 'clarksville parks and recreation',
 'estill springs police department',
 'watauga police department',
 'gallatin codes',
 'middleton police department',
 "bledsoe county sheriff's office",
 'parrotts chapel community fd',
 'lookout mountain police department',
 'decatur police department',
 'waldens ridge emergency service',
 'woodbury police department',
 'lebanon codes',
 'bedford county zoning',
 'mt. carmel police department',
 'surgoinsville police department',
 '10th judicial district drug task force',
 'rutherford police department',
 'whiteville police department',
 'dickson county emergency management',
 'bradley county building inspections',
 'grand junction police department',
 'moscow police department',
 'henry police department',
 'us department of veterans affairs, va police department',
 'rossville police department',
 'town of burns',
 'rutherford county building codes',
 "us department of energy's y12 national security complex",
 'winchester building and codes',
 'tusculum police department',
 'pioneer communications',
 'tennessee ridge police department',
 'collierville codes',
 'shelby county codes enf.',
 'wacker polysilicon north america',
 'trezevant police department',
 'legal and liability risk management institute',
 'namus',
 'peace officer standards and training commission',
 'collinwood police department',
 'gibson police department',
 'samburg police department',
 'winfield police department',
 'sevier county volunteer rescue squad',
 'gainesboro police department',
 'burns police department',
 'cross plains police department',
 'u.t. knoxville medical center police department',
 'walters state law enforcement training academy',
 'kimball police department',
 'mountain city police department',
 'dickson county planning, zoning and codes department',
 'rutherford county ema',
 'tennessee law enforcement training officers assoc.',
 'tennesee highway safety office',
 'pittman center police department',
 'new market police department',
 'cookeville codes department',
 'ridgely police department',
 'morristown codes (city of)',
 'sunbright police department',
 'policeone online academy (lexipol)',
 'jamestown police department',
 'middle tennessee drug task force',
 'hornbeak police department',
 'putnam county rescue squad',
 'tennesee department of intellectual and developmental disabilities (didd)',
 'tdot-knoxville',
 'shelbyville codes',
 'atf',
 'minor hill police department',
 'farmington/rich creek fd',
 'waverly police department',
 'memphis codes department',
 'tennesee department of correction',
 'baileyton police department',
 'illinois central railroad police department',
 'norfolk southern railroad police department',
 'hamilton county hazmat department',
 'crump police department',
 'wartburg police department',
 'clifton police department',
 'bulls gap police department',
 'murfreesboro building and codes',
 'white pine police department',
 'tennesee office of homeland security',
 'greeneville codes department',
 'grundy county ema',
 'macon county rescue squad',
 'crockett county 911',
 'robertson county office of planning',
 'department of homeland security/ immigration and customs',
 'williamson county ema',
 'eamc, fort gordon',
 'tennessee law enforcement agency (training)',
 'norris public works department',
 'north public safety',
 'forensic medical/davidson co.  medical examiner',
 'alamo police department',
 'fentress county ema',
 'hendersonville codes department',
 'mcminnville codes',
 'hawkins county emergency response team',
 'city of lexington',
 "city of parker's crossroads",
 'roane county code enforcement',
 'roane county constable',
 'associated architectural services',
 'department of  agriculture / division of foresty',
 'v-academy',
 'public entity partners (formerly tml risk management pool)',
 'lafollette codes',
 'washington county/johnson city ema',
 'columbia building inspections',
 'maryville codes',
 'jones lang lasalle',
 'a-pro home inspection services',
 'carlson home inspection services',
 'mid south dream homes llc.',
 'johnson and johnson builders inc.',
 'stop alarms inc.',
 'vintage homes llc.',
 'brad rainey homes',
 'sovereign homes llc.',
 'habitat for humanity of greater memphis',
 'nobles and olson construction',
 'ralph jones home plans, llc.',
 'gardo design group, llc.',
 'chamberlain and mccreeny',
 '421 area emergency services',
 'robert j. denley co.',
 'wright- lovitt, inc.',
 'rivercrest construction assoc.',
 'architechural custom works, llc.',
 'sullivan associates home designs',
 'faxon gillis homes',
 'david streeter construction, llc',
 'nesta custom homes, inc.',
 '2-10 home buyers warranty',
 'james a. hillard const. co',
 'ken garland co., inc',
 'the cowles company',
 'klazmer/sklar, llc',
 'jill hertz interior design',
 'savage construction',
 'yancey home builders, inc',
 'john hambrick builders',
 'meyers-bradick associates',
 'noland co.',
 'memphis s&d',
 'lenox homes',
 'university of tennessee/mtas',
 'cheatham county ema',
 'milan army plant/american ordinance',
 'white house codes',
 'maury county hazardous operations team',
 'jackson building and codes',
 'dyersburg codes enforcement',
 'hamblen county ema',
 'giles county e-911',
 'white county 911',
 'mcminn county rescue squad',
 'arlington development center',
 'clinch-powell resource conservation and dev. council',
 'east tennessee development district',
 'newport rescue squad',
 'knoxville building inspections',
 'clinton codes enforcement (city of)',
 'shelby state community college police deparmtent',
 'chattanooga housing authority',
 '31st judicial district drug task force',
 'coffee county codes department',
 'state of tennessee health facilities commission',
 'anderson county zoning',
 'oak ridge codes',
 'sparta codes',
 'warren county ema',
 'memphis light, gas and water division',
 'university of memphis/physical plant',
 'university of memphis/employee safety and health',
 'medical services of america',
 'tennessee association of rescue squads',
 'bernard and associates, pc',
 'alexander city police department',
 'camden police department',
 'knoxville-knox county emergency management',
 'van buren county ambulance service',
 'weakley county ema',
 'cleveland codes',
 'elizabethton codes',
 'knoxville codes',
 'charleston police department',
 '8th judicial district drug task force',
 'department of health jackson',
 'american health partners',
 'williamson county building codes',
 'pulaski codes',
 'springfield codes',
 'smyrna codes department',
 '84 lumber-components division',

In [36]:
def clean_type(df):
    df.loc[:, "type"] = df.type.str.replace(r"(\w+) $", r"\1", regex=True)
    return df 



newest_df = newest_df.pipe(clean_type)

newest_df.type.unique()

array([nan, 'Correction', 'Portal Update', 'Hire', 'Promotion',
       'Separation', 'Resigned in Good Standing', 'On Leave', 'Update',
       'Return from Leave', 'Re-Hire', 'Suspension',
       'Intradepartmental Transfer', 'Portal Update - Hire', 'Transfer',
       'Terminated', 'Return from Suspension', 'Demotion',
       'Resigned with Disciplinary Action Pending', 'On Leave (Medical)',
       'Resigned During Internal Investigation', 'Terminated for Cause',
       'Decertified', 'On Limited Duty'], dtype=object)