In [1]:
import pandas as pd

In [2]:
def clean_middle_name(df):
    df.loc[:, "middle_name"] = df.middle_name.str.replace(r"\.", "", regex=True)
    return df 

def read_tbl():
    df = pd.read_csv("../../../download/data/Tennessee/Tennessee_index.csv")

    df = df.rename(columns={"agcy_name": "agency_name"})

    df = df.pipe(clean_middle_name)

    df = df.drop(columns=["suffix"])

    df = df.fillna("")
    return df 

df = read_tbl()

df

,person_nbr,first_name,middle_name,last_name,agency_name,separation_reason,rank,type,status,start_date,end_date,full_name
0,0000-4863,MICHAEL,TRAVIS,HICKMAN,KINGSPORT POLICE DEPARTMENT,PROMOTION,CORPORAL,LAW ENFORCEMENT OFFICER,ACTIVE,1997-12-08,,MICHAEL TRAVIS HICKMAN
1,0000-5779,AUSTIN,O'BRIAN,EVANS,BENTON COUNTY SHERIFF'S OFFICE,SEPARATION,DEPUTY SHERIFF,LAW ENFORCEMENT OFFICER,TERMINATED,2022-10-17,2022-11-07,AUSTIN O'BRIAN EVANS
2,0000-6173,TRAVIS,DYLAN,WEBB,COCKE COUNTY SHERIFF'S OFFICE,PORTAL UPDATE,DETECTIVE,NAN,SEPARATED,2007-11-19,2015-08-03,TRAVIS DYLAN WEBB
3,0000-9571,ERNEST,WORTHAM,HILL,WILLIAMSON COUNTY SHERIFF'S OFFICE,HIRE,DEPUTY SHERIFF,LAW ENFORCEMENT OFFICER,ACTIVE,2013-07-08,,ERNEST WORTHAM HILL
4,0001-0693,JOHNNY,NAN,HANSEL,METRO NASHVILLE POLICE DEPARTMENT,SEPARATION,UNKNOWN,NAN,SEPARATED,1970-09-01,2100-01-01,JOHNNY HANSEL
...,...,...,...,...,...,...,...,...,...,...,...,...
60101,9998-1828,PHILLIP,STEPHEN,NARRAMORE,CHATTANOOGA POLICE DEPARTMENT,SEPARATION,POLICE OFFICER,LAW ENFORCEMENT OFFICER,RETIRED,1991-04-10,2020-12-31,PHILLIP STEPHEN NARRAMORE
60102,9998-3436,JACQUELINE,JO,WALLACE,CARROLL COUNTY SHERIFF'S OFFICE,RE-HIRE,INVESTIGATOR,LAW ENFORCEMENT OFFICER,ACTIVE,1999-10-28,,JACQUELINE JO WALLACE
60103,9998-4210,BRADY,PARKER,BROOKS,BARTLETT POLICE DEPARTMENT,SEPARATION,POLICE OFFICER,LAW ENFORCEMENT OFFICER,RESIGNED,1999-08-16,1999-11-03,BRADY PARKER BROOKS
60104,9998-4210,BRADY,PARKER,BROOKS,OAKLAND POLICE DEPARTMENT,SEPARATION,POLICE OFFICER,LAW ENFORCEMENT OFFICER,RESIGNED,2000-05-22,2000-09-05,BRADY PARKER BROOKS
60105,9998-4271,RITA,B,BAKER,METRO NASHVILLE POLICE DEPARTMENT,RE-HIRE,CAPTAIN,LAW ENFORCEMENT OFFICER,ACTIVE,1988-03-16,,RITA B. BAKER

In [3]:
df.to_csv("../data/output/tennessee_index.csv", index=False)