In [36]:
import pandas as pd

In [37]:
### date needs to be fixed

def read_tbl():
    df = pd.read_csv("../../../download/data/Utah/Utah_index.csv")

    df = df.rename(columns={"status": "separation_reason", "change_reason": "status", "agcy_name": "agency_name"})

    df = df.drop(columns=["birth_year", "age", "middle_initial"])
    return df 


df = read_tbl()

df

,person_nbr,full_name,last_name,first_name,middle_name,suffix,agency_name,type,rank,start_date,end_date,separation_reason,status
0,0001-0033,ALLEN C ACKERSON,ACKERSON,ALLEN,C,NaN,CENTERVILLE CITY POLICE DEPARTMENT,LAW ENFORCEMENT OFFICER,LAW ENFORCEMENT OFFICER,8/1/04,NaN,ACTIVE,UPDATE
1,0001-0035,NATHANIEL R ACHORD,ACHORD,NATHANIEL,R,NaN,DAVIS COUNTY SHERIFF'S OFFICE - SWORN,FULL TIME EMPLOYMENT,CORRECTIONAL OFFICER,2/16/07,7/24/08,RESIGNED,SEPARATION
2,0001-0046,EILEEN C CLARK,CLARK,EILEEN,C,NaN,UTAH STATE DEPARTMENT OF CORRECTIONS,FULL TIME EMPLOYMENT,CORRECTIONAL OFFICER,8/17/92,5/31/11,RESIGNED,SEPARATION
3,0001-0048,BRETT S MCCALL,MCCALL,BRETT,S,NaN,UTAH STATE DEPARTMENT OF CORRECTIONS,FULL TIME EMPLOYMENT,CORRECTIONAL OFFICER,12/15/95,1/4/09,TERMINATED,CHANGE OF STATUS
4,0001-0048,BRETT S MCCALL,MCCALL,BRETT,S,NaN,SANPETE COUNTY SHERIFF'S OFFICE,FULL TIME EMPLOYMENT,LAW ENFORCEMENT OFFICER,11/1/99,8/27/08,RESIGNED,SEPARATION
...,...,...,...,...,...,...,...,...,...,...,...,...,...
28695,9996-5458,WILLIAM LAWRENCE MARINONI,MARINONI,WILLIAM,LAWRENCE,NaN,UTAH STATE DEPARTMENT OF CORRECTIONS,FULL TIME EMPLOYMENT,CORRECTIONAL OFFICER,10/6/08,3/14/12,RESIGNED,CHANGE OF STATUS
28696,9996-5458,WILLIAM LAWRENCE MARINONI,MARINONI,WILLIAM,LAWRENCE,NaN,CARBON COUNTY SHERIFF'S OFFICE,LAW ENFORCEMENT OFFICER,LAW ENFORCEMENT OFFICER,3/16/12,6/13/23,SEPARATED,SEPARATION
28697,9996-5458,WILLIAM LAWRENCE MARINONI,MARINONI,WILLIAM,LAWRENCE,NaN,HELPER CITY POLICE DEPARTMENT,LAW ENFORCEMENT OFFICER,RESERVE,6/29/20,7/28/23,SEPARATED,SEPARATION
28698,9998-1013,CASH CURTIS RICKS,RICKS,CASH,CURTIS,NaN,WEBER COUNTY SHERIFF'S OFFICE,LAW ENFORCEMENT/CORRECTIONAL OFFICER,LAW ENFORCEMENT/CORRECTIONAL OFFICER,4/11/14,7/10/15,RESIGNED,CHANGE OF STATUS
28699,9998-1013,CASH CURTIS RICKS,RICKS,CASH,CURTIS,NaN,ROY POLICE DEPARTMENT,LAW ENFORCEMENT OFFICER,LAW ENFORCEMENT OFFICER,7/13/15,NaN,ACTIVE,UPDATE

In [38]:
df.to_csv("../data/output/utah_index.csv", index=False)

In [39]:
df.status.unique()

array(['UPDATE', 'SEPARATION', 'CHANGE OF STATUS', 'TRANSFER',
       'PORTAL UPDATE - HIRE', 'HIRE', 'RE-HIRE'], dtype=object)

In [40]:
df.separation_reason.unique()

array(['ACTIVE', 'RESIGNED', 'TERMINATED', 'SEPARATED', 'TRANSFER',
       'RESIGNED IN LIEU OF TERMINATION',
       'SEPARATED - INVESTIGATION REQUESTED', 'TRAINING SUSPENSION',
       'RESIGNED - INVESTIGATION REQUESTED', 'MILITARY LEAVE',
       'RESIGNED IN LIEU OF TERMINATION - INVESTIGATION REQUESTED',
       'TERMINATED - INVESTIGATION REQUESTED'], dtype=object)

In [41]:
df.isna().sum()

person_nbr               0
full_name                0
last_name                0
first_name               0
middle_name           2469
suffix               28192
agency_name              0
type                  2021
rank                     0
start_date               4
end_date             10421
separation_reason        0
status                   0
dtype: int64