In [1]:
import pandas as pd

In [2]:
def read_tbl():
    df = pd.read_csv("../../../download/data/Wyoming/wy-2023-index-enhanced.csv")

    df = df.drop(columns=["middle_name", "suffix", "year_of_birth", "age", "agency_city", "agency_state", "type"])

    df = df.rename(columns={"employment_status": "separation_reason", "agency_type": "type", "agency": "agency_name"})


    return df 


df = read_tbl()

df

,person_nbr,full_name,first_name,last_name,agency_name,rank,start_date,end_date,person_status,employment_type,separation_reason,primary_employment,type
0,0000-4417,MICHAEL SCHINDLER,MICHAEL,SCHINDLER,PARK COUNTY SHERIFF'S OFFICE,DETENTION OFFICER,2023-05-05,NaN,ACTIVE,FULL TIME,ACTIVE,True,SHERIFF OFFICES
1,0004-0627,ALAN KIRK,ALAN,KIRK,NATRONA COUNTY SHERIFF'S OFFICE,RESERVE DETENTION OFFICER,2018-01-02,NaN,ACTIVE,RESERVE,ACTIVE,False,SHERIFF OFFICES
2,0004-0627,ALAN KIRK,ALAN,KIRK,NATRONA COUNTY SHERIFF'S OFFICE,PEACE OFFICER,2012-09-06,NaN,ACTIVE,FULL TIME,ACTIVE,True,SHERIFF OFFICES
3,0005-3387,JOHN GUTIERREZ,JOHN,GUTIERREZ,LARAMIE COUNTY COMBINED COMMUNICATIONS CENTER,DISPATCHER,2005-07-01,NaN,ACTIVE,FULL TIME,ACTIVE,True,COMMUNICATIONS
4,0005-3387,JOHN GUTIERREZ,JOHN,GUTIERREZ,OTHER EMPLOYMENT (NON-WYOMING),DISPATCHER,2002-03-01,2004-06-30,ACTIVE,FULL TIME,SEPARATED,False,OTHER
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11628,9988-7500,TODD MORGAN,TODD,MORGAN,JACKSON POLICE DEPARTMENT,PEACE OFFICER,2014-07-07,NaN,ACTIVE,FULL TIME,ACTIVE,True,POLICE DEPARTMENTS
11629,9995-2684,SANDRA ARNOLD,SANDRA,ARNOLD,WYOMING HIGHWAY PATROL,PEACE OFFICER,2010-08-16,NaN,INACTIVE,FULL TIME,ACTIVE,True,STATE AGENCIES
11630,9996-5444,DUSTIN KIRSCH,DUSTIN,KIRSCH,WYOMING GAME AND FISH DEPARTMENT,PEACE OFFICER,2023-04-06,NaN,ACTIVE,FULL TIME,ACTIVE,True,STATE AGENCIES
11631,9996-5444,DUSTIN KIRSCH,DUSTIN,KIRSCH,CONVERSE COUNTY SHERIFF'S OFFICE,PEACE OFFICER,2009-07-17,2023-03-31,ACTIVE,FULL TIME,SEPARATED,False,SHERIFF OFFICES
11632,9996-5444,DUSTIN KIRSCH,DUSTIN,KIRSCH,CONVERSE COUNTY SHERIFF'S OFFICE,DETENTION OFFICER,2008-01-02,2023-03-31,ACTIVE,PART TIME,SEPARATED,False,SHERIFF OFFICES

In [3]:
df.to_csv("../data/output/wyoming_index.csv", index=False)