In [6]:
import pandas as pd

In [7]:
def clean_middle_name(df):
    df.loc[:, "middle_name"] = df.middle_name.str.replace(r"\.", "", regex=True)
    return df 

def read_tbl():
    df = pd.read_csv("../../../download/data/Ohio/Ohio_index.csv")

    df = df.pipe(clean_middle_name)
    
    df = df.drop(columns=["type"])

    df = df.rename(columns={"agency": "agency_name"})
    return df 


df = read_tbl()

df

,person_nbr,full_name,first_name,middle_name,last_name,suffix,year_of_birth,age,agency_name,rank,start_date,end_date
0,133346,Jason R Aamodt,Jason,R,Aamodt,NaN,1969.0,54.0,Reynoldsburg Police Department,Full-time,2000-08-18,2022-05-20
1,213156,William Everett Aaron Jr,William,Everett,Aaron,Jr,1994.0,29.0,Goshen Twp. Police Department - Mahoning,Part-time,2016-09-12,2017-03-30
2,213156,William Everett Aaron Jr,William,Everett,Aaron,Jr,1994.0,29.0,Mill Creek MetroParks Police Department,Reserve,2019-11-22,2020-06-10
3,213156,William Everett Aaron Jr,William,Everett,Aaron,Jr,1994.0,29.0,Mill Creek MetroParks Police Department,Full-time,2020-06-10,2021-09-30
4,213156,William Everett Aaron Jr,William,Everett,Aaron,Jr,1994.0,29.0,Mahoning County Sheriff's Office,Reserve,2021-01-22,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
145100,177560,Zachary Paul Zwolinski,Zachary,Paul,Zwolinski,NaN,1987.0,37.0,North Randall Police Department,Auxiliary,2013-03-25,2015-09-28
145101,177560,Zachary Paul Zwolinski,Zachary,Paul,Zwolinski,NaN,1987.0,37.0,Orange Village Police Department,Part-time,2014-03-12,2015-09-09
145102,177560,Zachary Paul Zwolinski,Zachary,Paul,Zwolinski,NaN,1987.0,37.0,Orange Village Police Department,Full-time,2015-09-09,NaN
145103,133925,Thomas L. Zywczyk,Thomas,L,Zywczyk,NaN,1976.0,47.0,Columbus Police Department,Full-time,2001-01-05,2007-02-09
145104,133925,Thomas L. Zywczyk,Thomas,L,Zywczyk,NaN,1976.0,47.0,Pickerington Police Department,Auxiliary,2007-11-01,2008-07-01

In [8]:
df.isna().sum()

person_nbr            0
full_name             0
first_name            0
middle_name        5675
last_name             0
suffix           136951
year_of_birth        37
age                  37
agency_name           0
rank                  0
start_date           27
end_date          35096
dtype: int64